"""Download or generate benchmark task repos."""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

TASK_REPOS: dict[str, dict[str, str]] = {
    "skillsbench": {
        "repo": "https://github.com/benchflow-ai/skillsbench.git",
        "ref": "main",
        "subdir": "tasks",
    },
}

# Benchmarks whose tasks are generated by a local script rather than cloned.
_GENERATED_BENCHMARKS: dict[str, dict[str, str]] = {
    "programbench": {
        "repo": "https://github.com/facebookresearch/programbench.git",
        "subdir": "tasks",
    },
}


def _repo_root() -> Path:
    """Find the repo root via .git directory."""
    d = Path.cwd()
    while d != d.parent:
        if (d / ".git").exists():
            return d
        d = d.parent
    return Path.cwd()


def ensure_tasks(benchmark: str) -> Path:
    """Ensure benchmark tasks are available locally.

    Cloned benchmarks go into ``benchmarks/<name>/``; generated benchmarks
    (e.g. ``programbench``) go into ``benchmarks/<name>/tasks/``.

    Always resolves paths relative to the repo root.
    """
    if benchmark in _GENERATED_BENCHMARKS:
        return _ensure_generated(benchmark)

    if benchmark not in TASK_REPOS:
        available = sorted({*TASK_REPOS, *_GENERATED_BENCHMARKS})
        raise ValueError(f"Unknown benchmark: {benchmark!r}. Available: {available}")

    info = TASK_REPOS[benchmark]
    root = _repo_root()
    target = root / "benchmarks" / benchmark / (info.get("subdir") or "")

    if target.exists() and any(target.iterdir()):
        return target

    logger.info("Downloading %s tasks from %s...", benchmark, info["repo"])
    target.parent.mkdir(parents=True, exist_ok=True)
    clone_dir = root / "benchmarks" / benchmark / "_clone"

    try:
        clone_cmd = ["git", "clone", "--depth", "1"]
        if ref := info.get("ref"):
            clone_cmd.extend(["--branch", ref])
        clone_cmd.extend([info["repo"], str(clone_dir)])
        subprocess.run(clone_cmd, check=True)
        if info.get("subdir"):
            (clone_dir / info["subdir"]).rename(target)
        else:
            shutil.rmtree(clone_dir / ".git")
            clone_dir.rename(target)
    finally:
        if clone_dir.exists():
            shutil.rmtree(clone_dir, ignore_errors=True)

    logger.info(
        "Downloaded %d tasks to %s",
        sum(1 for d in target.iterdir() if d.is_dir()),
        target,
    )
    return target


def _ensure_generated(benchmark: str) -> Path:
    """Clone upstream repo, run the generator, return the tasks directory."""
    info = _GENERATED_BENCHMARKS[benchmark]
    root = _repo_root()
    target = root / "benchmarks" / benchmark / (info.get("subdir") or "")

    if target.exists() and any(target.iterdir()):
        return target

    logger.info("Generating %s tasks from %s...", benchmark, info["repo"])
    clone_dir = root / "benchmarks" / benchmark / "_clone"
    clone_dir.parent.mkdir(parents=True, exist_ok=True)

    # Generate into a temp directory and rename atomically so partial
    # failures never leave a cached target that looks complete.
    staging = root / "benchmarks" / benchmark / "_gen_staging"
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", info["repo"], str(clone_dir)],
            check=True,
        )
        pb_tasks = clone_dir / "src" / "programbench" / "data" / "tasks"
        if not pb_tasks.is_dir():
            raise FileNotFoundError(
                f"ProgramBench tasks directory not found at {pb_tasks}"
            )

        import importlib
        import sys

        gen_path = root / "benchmarks" / "programbench"
        if str(gen_path.parent) not in sys.path:
            sys.path.insert(0, str(gen_path.parent))
        generate = importlib.import_module("programbench.benchflow")

        staging.mkdir(parents=True, exist_ok=True)
        generated = generate.generate_all(pb_tasks, staging)

        # Atomic swap: only expose target once generation fully succeeds
        target.parent.mkdir(parents=True, exist_ok=True)
        staging.rename(target)
        logger.info("Generated %d tasks to %s", len(generated), target)
    finally:
        if clone_dir.exists():
            shutil.rmtree(clone_dir, ignore_errors=True)
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)

    return target
